server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/iplatform-ai?socketTimeout=60000&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: casit@Mysql
      max-lifetime: 120000
      idle-timeout: 30000
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource